### ISSUE TITLE
docker-compose-local-eosio1.0.yaml has "llegal multibyte sequence" 

### ISSUE THREAD

**Issue by ccccbjcn** [shanlusun/blockchain#6]
```
$ docker-compose -f docker-compose-local-eosio1.0.yaml up -d
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 41, in project_from_options
  File "compose\cli\command.py", line 109, in get_project
  File "compose\config\config.py", line 283, in find
  File "compose\config\config.py", line 283, in <listcomp>
  File "compose\config\config.py", line 183, in from_filename
  File "compose\config\config.py", line 1434, in load_yaml
  File "site-packages\yaml\__init__.py", line 94, in safe_load
  File "site-packages\yaml\__init__.py", line 70, in load
  File "site-packages\yaml\loader.py", line 24, in __init__
  File "site-packages\yaml\reader.py", line 85, in __init__
  File "site-packages\yaml\reader.py", line 124, in determine_encoding
  File "site-packages\yaml\reader.py", line 178, in update_raw
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 249: illegal multibyte sequence
[11624] Failed to execute script docker-compose
```
git diff
```
$ git diff
diff --git a/eos/04/docker/docker-compose-local-eosio1.0.yaml b/eos/04/docker/docker-compose-local-eosio1.0.yaml
index 672bdb9..a9f2e2a 100644
--- a/eos/04/docker/docker-compose-local-eosio1.0.yaml
+++ b/eos/04/docker/docker-compose-local-eosio1.0.yaml
@@ -3,7 +3,7 @@ version: "3"
 services:
   nodeosd:
     image: eosio/eos-dev:latest
-    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --delete-all-blocks #--genesis-json /opt/eosio/bin/data-dir/genesis.json #--contracts-console #-e — Enable block production, even if the chain is stale
+    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --delete-all-blocks #--genesis-json /opt/eosio/bin/data-dir/genesis.json #--contracts-console #-e -- Enable block production, even if the chain is stale
     hostname: nodeosd
     ports:
       - 8888:8888
```

**Comment by shanlusun** [comment]
这个#注释里面的 差异会引起问题？ 我这边docker-ompose启动使用docker-compose-local-eosio1.0.yaml没有遇到任何问题。

`docker-compose -v              
docker-compose version 1.21.2, build a133471`

**Comment by shanlusun** [comment]
这个”—“在注释里面，会影响你的docker-compose 运行？ 我这里是完全没问题，我close 了。
